{% set name = "llama-index-llms-openai" %}
{% set version = "0.3.13" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/llama_index_llms_openai-{{ version }}.tar.gz
    sha256: 51dda240dae7671c37e84bb50fe77fe6bb58a9b2a7e33dccd84473c9998afcea
  # https://github.com/run-llama/llama_index/issues/10806
  - url: https://raw.githubusercontent.com/run-llama/llama_index/main/LICENSE
    sha256: 24f40b5190fdacabc24ddbb5f76364d15e4f030925220ea300d8a2dd4993c8cb

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - poetry-core
    - pip
  run:
    - openai >=1.58.1,<2.0.0
    - python >={{ python_min }},<4.0
    - llama-index-core >=0.12.4,<0.13.0

test:
  imports:
    - llama_index.llms.openai
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://llamaindex.ai
  dev_url: https://github.com/run-llama/llama_index/tree/main/llama-index-integrations/llms/llama-index-llms-openai
  summary: llama-index llms openai integration
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
    - pavelzw
